/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RoupeiroRouteImport } from './routes/roupeiro'
import { Route as OutfitsRouteImport } from './routes/outfits'
import { Route as CriadorRouteImport } from './routes/criador'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiScrapeProductRouteImport } from './routes/api/scrape-product'

const RoupeiroRoute = RoupeiroRouteImport.update({
  id: '/roupeiro',
  path: '/roupeiro',
  getParentRoute: () => rootRouteImport,
} as any)
const OutfitsRoute = OutfitsRouteImport.update({
  id: '/outfits',
  path: '/outfits',
  getParentRoute: () => rootRouteImport,
} as any)
const CriadorRoute = CriadorRouteImport.update({
  id: '/criador',
  path: '/criador',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiScrapeProductRoute = ApiScrapeProductRouteImport.update({
  id: '/api/scrape-product',
  path: '/api/scrape-product',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/criador': typeof CriadorRoute
  '/outfits': typeof OutfitsRoute
  '/roupeiro': typeof RoupeiroRoute
  '/api/scrape-product': typeof ApiScrapeProductRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/criador': typeof CriadorRoute
  '/outfits': typeof OutfitsRoute
  '/roupeiro': typeof RoupeiroRoute
  '/api/scrape-product': typeof ApiScrapeProductRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/criador': typeof CriadorRoute
  '/outfits': typeof OutfitsRoute
  '/roupeiro': typeof RoupeiroRoute
  '/api/scrape-product': typeof ApiScrapeProductRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/criador' | '/outfits' | '/roupeiro' | '/api/scrape-product'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/criador' | '/outfits' | '/roupeiro' | '/api/scrape-product'
  id:
    | '__root__'
    | '/'
    | '/criador'
    | '/outfits'
    | '/roupeiro'
    | '/api/scrape-product'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CriadorRoute: typeof CriadorRoute
  OutfitsRoute: typeof OutfitsRoute
  RoupeiroRoute: typeof RoupeiroRoute
  ApiScrapeProductRoute: typeof ApiScrapeProductRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/roupeiro': {
      id: '/roupeiro'
      path: '/roupeiro'
      fullPath: '/roupeiro'
      preLoaderRoute: typeof RoupeiroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/outfits': {
      id: '/outfits'
      path: '/outfits'
      fullPath: '/outfits'
      preLoaderRoute: typeof OutfitsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/criador': {
      id: '/criador'
      path: '/criador'
      fullPath: '/criador'
      preLoaderRoute: typeof CriadorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/scrape-product': {
      id: '/api/scrape-product'
      path: '/api/scrape-product'
      fullPath: '/api/scrape-product'
      preLoaderRoute: typeof ApiScrapeProductRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CriadorRoute: CriadorRoute,
  OutfitsRoute: OutfitsRoute,
  RoupeiroRoute: RoupeiroRoute,
  ApiScrapeProductRoute: ApiScrapeProductRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
